### ISSUE TITLE
How to call model in controller?

### ISSUE THREAD

**Issue by vinaysikarwar** [kamilhurajt/Phalcon-autorouter#1]
Hi,

I have used you auto router module, done some changes as per my needs. Can you please help me in solving two current issues.
1. I have used the module system, but how do i use multiple controller in this. What i have seen it seems that for every controller , every action i have to set in config.
2. How to i call model in controller. For saving form and other things.

It will be very help full if you can help me into this.

Thanks

**Comment by ghost** [comment]
Can you show me some example what you need ?

**Comment by ghost** [comment]
For 1. It's isnt have configuraiton for any controller in config. In config you can configure just main information about module to load, controllers are mached by URL and file existence, so you can simply create lot of controllers as you want, the plugin will automaticaly loads all controllers and actions into routing, then you can access the action and resourse by url, and plugin will find that.

But, as soon as possible i will push new version of autoroute plugin, the version will be support to load action, controllers and modules in url called like that: my-module/my-resource/my-action/ and other bug fixes.

**Comment by vinaysikarwar** [comment]
1. Currently what is happening, I have created a user module, then for each action I have to define it in config. 
   array(
                   'moduleName' => 'User',
                   'baseUrl' => 'user/',
                   'defaultController' => 'user',
                   'defaultAction' => 'index'
               ),
           array(
                   'moduleName' => 'User',
                   'baseUrl' => 'user/login',
                   'defaultController' => 'user',
                   'defaultAction' => 'login'
               ) 
2. I am not getting a way of calling a model class in controller

**Comment by vinaysikarwar** [comment]
If you want i can provide the repository access

**Comment by ghost** [comment]
It's not correct to have defined to any resource and action configuration. 

Define just User module, then, create indexController and inside create indexAction, loginAction and more action which u need and when you access to /user/ url the autoroute3 plugin will forward it to UserModule and indexController and indexAction.

When you access to URL /user/login/ the plugin will forward you to: UserModule , indexController with loginAction, no other configurations are needed...

**Comment by vinaysikarwar** [comment]
Now routing is working fine, but my issue is how to call model class in controller.

In Simple View I was calling model as 
$model = new Users;

But now when i am doing the same it throws and error
Fatal error: Class 'Frontend\Controller\Users' not found in /app/FrontendModule/controller/PostsController.php on line 8

**Comment by vinaysikarwar** [comment]
I found solution by using  
new \Frontend\Model\Users;

Any ways thanks for your great work.

**Comment by vinaysikarwar** [comment]
I have one more question, how can i register a new helper, so that  I can call ts functions any where.

**Comment by ghost** [comment]
To call object, you must use namespace and call object with full path and namespace eg: 
\Namespace\Object();

To register new helper, i'm not sure what you meant with "helper" but to register object or service you can see phalconphp documentation how to configure bootstrap, in bootstrap you can register service into DI container, the service will be accessable from controller. ( $this->service or $this->getMyService() )
