### ISSUE TITLE
Can you help me in changing the module path directory

### ISSUE THREAD

**Issue by vinaysikarwar** [kamilhurajt/Phalcon-autorouter#2]
Hi,

There is one request for you.

Currently as per your module you have added the adminModule and frontendModule.

I want the dir structure like 
app/modules/core/admin
app/modules/core/frontend

Thanks

**Comment by ghost** [comment]
Hi, new release ar here, try to use the new release maybe it will help you resolve your problems. 
Old release just work with phalcon < 2 this new works with phalcon 2.0.

**Comment by ghost** [comment]
Structure of your file you can set in configuration file.
